# Generated by Django 4.0.4 on 2022-04-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='numplate_checkin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numplate_num', models.CharField(max_length=12)),
                ('check_in_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='numplate_checkout_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numplate_num', models.CharField(max_length=12)),
                ('check_out_time', models.DateTimeField()),
            ],
        ),
    ]
