# Generated by Django 4.0.4 on 2022-04-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numplate_checkin_data',
            name='car_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='numplate_checkin_data',
            name='numplate_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='numplate_checkout_data',
            name='car_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='numplate_checkout_data',
            name='numplate_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
