# Generated by Django 4.0.4 on 2022-04-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0002_numplate_checkin_data_car_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numplate_checkin_data',
            name='numplate_img',
        ),
        migrations.AlterField(
            model_name='numplate_checkin_data',
            name='numplate_num',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='numplate_checkout_data',
            name='numplate_num',
            field=models.CharField(max_length=30),
        ),
    ]
