# Generated by Django 4.0.4 on 2022-04-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0003_remove_numplate_checkin_data_numplate_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numplate_checkin_data',
            name='car_img',
            field=models.FileField(upload_to=''),
        ),
    ]
