# Generated by Django 4.0.4 on 2022-04-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0004_alter_numplate_checkin_data_car_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numplate_checkin_data',
            name='car_img',
        ),
        migrations.RemoveField(
            model_name='numplate_checkout_data',
            name='car_img',
        ),
        migrations.RemoveField(
            model_name='numplate_checkout_data',
            name='numplate_img',
        ),
    ]
